service: sledz-paczke

provider:
  name: aws
  stage: dev
  runtime: nodejs12.x
  profile: ${self:custom.myProfile.${self:custom.myStage}}
  region: ${self:custom.myRegion.${self:custom.myStage}}

custom:
  myStage: ${opt:stage, self:provider.stage}
  myProfile:
    dev: default
    prod: default
  myRegion:
    dev: us-east-2
    prod: us-east-2

functions:
  checkPackage:
    handler: src/checkPackage/lambda.main
    description: Checks package info on website 
    memorySize: 128
    timeout: 25